#version: '3.7'
#services:
#  mongodb_container:
#    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: mongopw
#    ports:
#      - 27017:27017
#    volumes:
#      - mongodb_data_container:/data/db
#
#volumes:
#  mongodb_data_container:

version: '3.7'

services:
#  delivery-mvp:
#    image: delivery-mvp:latest
#    container_name: delivery
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - database
#    ports:
#      - "8099:8099"
#    networks:
#      - mvp-network

#  delivery-mvp:
#    image: delivery-mvp:latest
#    container_name: delivery
#    build: .
#    ports:
#      - '8099:8099'
#    depends_on:
#      - database
#    networks:
#      - mvp-network

  database:
    image: 'postgres:latest'
    container_name: 'db'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_database_1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 1s
    networks:
      - mvp-network

networks:
  mvp-network:
    driver: bridge