package com.mvp.delivery.delivery.infrastruture.repository.auth

import com.mvp.delivery.delivery.infrastruture.entity.auth.ApplicationSecretAuthorityEntity
import org.springframework.data.r2dbc.repository.R2dbcRepository

interface IApplicationSecretAuthorityRepository: R2dbcRepository<ApplicationSecretAuthorityEntity, String>