
server:
  port: 8099
  error:
    include-message: always

spring-doc:
  swagger-ui:
    path: /swagger-ui.html

#

#  sql:
#    init:
#      schema-locations: classpath:init.sql
#      mode: always
