
server:
  port: 8099
  error:
    include-message: always

spring-doc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  docker:
    compose:
      file: "./docker-compose.yml"
#

#  sql:
#    init:
#      schema-locations: classpath:
#      mode: always
