server:
  port: 8099
  error:
    include-message: always

spring-doc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  docker:
    compose:
      file: "docker-compose.yml"

logging:
  level:
    root:
      org.springframework.web: "debug"
      org.hibernate: "debug"
