apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      name: delivery
      labels:
        app: delivery
    spec:
      containers:
        - name:  delivery
          image: lfneves/delivery-mvp:0.0.6
          ports:
            - containerPort: 8099
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_HOST
      imagePullSecrets:
        - name: secret-dockerhub
