apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJHWnVaWFpsY3k1a1owQm5iV0ZwYkM1amIyMDZaR05yY2w5d1lYUmZkSGRyUkhWc2JsUjFZamhVWDBweWR6aGpVRko0V1dkRFlYVTAiCgkJfQoJfQp9
kind: Secret
metadata:
  name: secret-dockerhub
  namespace: default
type: kubernetes.io/dockerconfigjson
