apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: delivery
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      name: delivery
      labels:
        app: delivery
    spec:
      containers:
        - name:  {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{.Values.service.port}}
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-secret-credentials
                  key: POSTGRES_HOST
          resources:
            requests:
              cpu: 20m
              memory: 500Mi
      imagePullSecrets:
        - name: secret-dockerhub
